// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"
	"github.com/odeyaio/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomService is an autogenerated mock type for the roomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomService
func (_mock *MockRoomService) Create(ctx context.Context, name string, description *string, capacity *int) (model.Room, error) {
	ret := _mock.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) (model.Room, error)); ok {
		return returnFunc(ctx, name, description, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) model.Room); ok {
		r0 = returnFunc(ctx, name, description, capacity)
	} else {
		r0 = ret.Get(0).(model.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, *int) error); ok {
		r1 = returnFunc(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - capacity *int
func (_e *MockRoomService_Expecter) Create(ctx any, name any, description any, capacity any) *MockRoomService_Create_Call {
	return &MockRoomService_Create_Call{Call: _e.mock.On("Create", ctx, name, description, capacity)}
}

func (_c *MockRoomService_Create_Call) Run(run func(ctx context.Context, name string, description *string, capacity *int)) *MockRoomService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRoomService_Create_Call) Return(room model.Room, err error) *MockRoomService_Create_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomService_Create_Call) RunAndReturn(run func(ctx context.Context, name string, description *string, capacity *int) (model.Room, error)) *MockRoomService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomService
func (_mock *MockRoomService) List(ctx context.Context) ([]model.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomService_Expecter) List(ctx any) *MockRoomService_List_Call {
	return &MockRoomService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomService_List_Call) Run(run func(ctx context.Context)) *MockRoomService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomService_List_Call) Return(rooms []model.Room, err error) *MockRoomService_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomService_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Room, error)) *MockRoomService_List_Call {
	_c.Call.Return(run)
	return _c
}
