// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"
	"github.com/google/uuid"
	"github.com/odeyaio/booking-service/internal/model"
	"github.com/odeyaio/booking-service/internal/pagination"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingService is an autogenerated mock type for the bookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Cancel(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) (model.Booking, error) {
	ret := _mock.Called(ctx, userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)); ok {
		return returnFunc(ctx, userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Booking); ok {
		r0 = returnFunc(ctx, userID, bookingID)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockBookingService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - bookingID uuid.UUID
func (_e *MockBookingService_Expecter) Cancel(ctx any, userID any, bookingID any) *MockBookingService_Cancel_Call {
	return &MockBookingService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, userID, bookingID)}
}

func (_c *MockBookingService_Cancel_Call) Run(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID)) *MockBookingService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_Cancel_Call) Return(booking model.Booking, err error) *MockBookingService_Cancel_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Cancel_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) (model.Booking, error)) *MockBookingService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Create(ctx context.Context, userID uuid.UUID, slotID uuid.UUID) (model.Booking, error) {
	ret := _mock.Called(ctx, userID, slotID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)); ok {
		return returnFunc(ctx, userID, slotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Booking); ok {
		r0 = returnFunc(ctx, userID, slotID)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, slotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - slotID uuid.UUID
func (_e *MockBookingService_Expecter) Create(ctx any, userID any, slotID any) *MockBookingService_Create_Call {
	return &MockBookingService_Create_Call{Call: _e.mock.On("Create", ctx, userID, slotID)}
}

func (_c *MockBookingService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, slotID uuid.UUID)) *MockBookingService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_Create_Call) Return(booking model.Booking, err error) *MockBookingService_Create_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, slotID uuid.UUID) (model.Booking, error)) *MockBookingService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBookingService
func (_mock *MockBookingService) List(ctx context.Context, params pagination.Params) ([]model.Booking, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pagination.Params) ([]model.Booking, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pagination.Params) []model.Booking); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pagination.Params) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, pagination.Params) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params pagination.Params
func (_e *MockBookingService_Expecter) List(ctx any, params any) *MockBookingService_List_Call {
	return &MockBookingService_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockBookingService_List_Call) Run(run func(ctx context.Context, params pagination.Params)) *MockBookingService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pagination.Params
		if args[1] != nil {
			arg1 = args[1].(pagination.Params)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_List_Call) Return(bookings []model.Booking, n int, err error) *MockBookingService_List_Call {
	_c.Call.Return(bookings, n, err)
	return _c
}

func (_c *MockBookingService_List_Call) RunAndReturn(run func(ctx context.Context, params pagination.Params) ([]model.Booking, int, error)) *MockBookingService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListMy provides a mock function for the type MockBookingService
func (_mock *MockBookingService) ListMy(ctx context.Context, userID uuid.UUID) ([]model.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMy")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_ListMy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMy'
type MockBookingService_ListMy_Call struct {
	*mock.Call
}

// ListMy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBookingService_Expecter) ListMy(ctx any, userID any) *MockBookingService_ListMy_Call {
	return &MockBookingService_ListMy_Call{Call: _e.mock.On("ListMy", ctx, userID)}
}

func (_c *MockBookingService_ListMy_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBookingService_ListMy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_ListMy_Call) Return(bookings []model.Booking, err error) *MockBookingService_ListMy_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingService_ListMy_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.Booking, error)) *MockBookingService_ListMy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomService is an autogenerated mock type for the roomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomService
func (_mock *MockRoomService) Create(ctx context.Context, name string, description *string, capacity *int) (model.Room, error) {
	ret := _mock.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) (model.Room, error)); ok {
		return returnFunc(ctx, name, description, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) model.Room); ok {
		r0 = returnFunc(ctx, name, description, capacity)
	} else {
		r0 = ret.Get(0).(model.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, *int) error); ok {
		r1 = returnFunc(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - capacity *int
func (_e *MockRoomService_Expecter) Create(ctx any, name any, description any, capacity any) *MockRoomService_Create_Call {
	return &MockRoomService_Create_Call{Call: _e.mock.On("Create", ctx, name, description, capacity)}
}

func (_c *MockRoomService_Create_Call) Run(run func(ctx context.Context, name string, description *string, capacity *int)) *MockRoomService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRoomService_Create_Call) Return(room model.Room, err error) *MockRoomService_Create_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomService_Create_Call) RunAndReturn(run func(ctx context.Context, name string, description *string, capacity *int) (model.Room, error)) *MockRoomService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomService
func (_mock *MockRoomService) List(ctx context.Context) ([]model.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomService_Expecter) List(ctx any) *MockRoomService_List_Call {
	return &MockRoomService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomService_List_Call) Run(run func(ctx context.Context)) *MockRoomService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomService_List_Call) Return(rooms []model.Room, err error) *MockRoomService_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomService_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Room, error)) *MockRoomService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleService creates a new instance of MockScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleService {
	mock := &MockScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleService is an autogenerated mock type for the scheduleService type
type MockScheduleService struct {
	mock.Mock
}

type MockScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleService) EXPECT() *MockScheduleService_Expecter {
	return &MockScheduleService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockScheduleService
func (_mock *MockScheduleService) Create(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string) (model.Schedule, error) {
	ret := _mock.Called(ctx, roomID, daysOfWeek, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) (model.Schedule, error)); ok {
		return returnFunc(ctx, roomID, daysOfWeek, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) model.Schedule); ok {
		r0 = returnFunc(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		r0 = ret.Get(0).(model.Schedule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []int, string, string) error); ok {
		r1 = returnFunc(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScheduleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - daysOfWeek []int
//   - startTime string
//   - endTime string
func (_e *MockScheduleService_Expecter) Create(ctx any, roomID any, daysOfWeek any, startTime any, endTime any) *MockScheduleService_Create_Call {
	return &MockScheduleService_Create_Call{Call: _e.mock.On("Create", ctx, roomID, daysOfWeek, startTime, endTime)}
}

func (_c *MockScheduleService_Create_Call) Run(run func(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string)) *MockScheduleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockScheduleService_Create_Call) Return(schedule model.Schedule, err error) *MockScheduleService_Create_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleService_Create_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string) (model.Schedule, error)) *MockScheduleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotService creates a new instance of MockSlotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotService {
	mock := &MockSlotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotService is an autogenerated mock type for the slotService type
type MockSlotService struct {
	mock.Mock
}

type MockSlotService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotService) EXPECT() *MockSlotService_Expecter {
	return &MockSlotService_Expecter{mock: &_m.Mock}
}

// ListAvailable provides a mock function for the type MockSlotService
func (_mock *MockSlotService) ListAvailable(ctx context.Context, roomID uuid.UUID, dateString string) ([]model.Slot, error) {
	ret := _mock.Called(ctx, roomID, dateString)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.Slot, error)); ok {
		return returnFunc(ctx, roomID, dateString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.Slot); ok {
		r0 = returnFunc(ctx, roomID, dateString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, roomID, dateString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotService_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type MockSlotService_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - dateString string
func (_e *MockSlotService_Expecter) ListAvailable(ctx any, roomID any, dateString any) *MockSlotService_ListAvailable_Call {
	return &MockSlotService_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, roomID, dateString)}
}

func (_c *MockSlotService_ListAvailable_Call) Run(run func(ctx context.Context, roomID uuid.UUID, dateString string)) *MockSlotService_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlotService_ListAvailable_Call) Return(slots []model.Slot, err error) *MockSlotService_ListAvailable_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockSlotService_ListAvailable_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, dateString string) ([]model.Slot, error)) *MockSlotService_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the userService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockUserService
func (_mock *MockUserService) Login(ctx context.Context, email string, password string) (model.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserService_Expecter) Login(ctx any, email any, password any) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(user model.User, err error) *MockUserService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (model.User, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, email string, password string, roleID model.RoleID) (model.User, error) {
	ret := _mock.Called(ctx, email, password, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.RoleID) (model.User, error)); ok {
		return returnFunc(ctx, email, password, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.RoleID) model.User); ok {
		r0 = returnFunc(ctx, email, password, roleID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.RoleID) error); ok {
		r1 = returnFunc(ctx, email, password, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - roleID model.RoleID
func (_e *MockUserService_Expecter) Register(ctx any, email any, password any, roleID any) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, roleID)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, email string, password string, roleID model.RoleID)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.RoleID
		if args[3] != nil {
			arg3 = args[3].(model.RoleID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(user model.User, err error) *MockUserService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string, roleID model.RoleID) (model.User, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
