// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"
	"github.com/odeyaio/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleRepository is an autogenerated mock type for the scheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockScheduleRepository
func (_mock *MockScheduleRepository) List(ctx context.Context) ([]model.Schedule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Schedule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Schedule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockScheduleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScheduleRepository_Expecter) List(ctx any) *MockScheduleRepository_List_Call {
	return &MockScheduleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockScheduleRepository_List_Call) Run(run func(ctx context.Context)) *MockScheduleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduleRepository_List_Call) Return(schedules []model.Schedule, err error) *MockScheduleRepository_List_Call {
	_c.Call.Return(schedules, err)
	return _c
}

func (_c *MockScheduleRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Schedule, error)) *MockScheduleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotGenerator creates a new instance of MockSlotGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotGenerator {
	mock := &MockSlotGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotGenerator is an autogenerated mock type for the slotGenerator type
type MockSlotGenerator struct {
	mock.Mock
}

type MockSlotGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotGenerator) EXPECT() *MockSlotGenerator_Expecter {
	return &MockSlotGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockSlotGenerator
func (_mock *MockSlotGenerator) Generate(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time) error {
	ret := _mock.Called(ctx, schedule, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Schedule, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, schedule, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSlotGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockSlotGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule model.Schedule
//   - from time.Time
//   - to time.Time
func (_e *MockSlotGenerator_Expecter) Generate(ctx any, schedule any, from any, to any) *MockSlotGenerator_Generate_Call {
	return &MockSlotGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, schedule, from, to)}
}

func (_c *MockSlotGenerator_Generate_Call) Run(run func(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time)) *MockSlotGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Schedule
		if args[1] != nil {
			arg1 = args[1].(model.Schedule)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotGenerator_Generate_Call) Return(err error) *MockSlotGenerator_Generate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSlotGenerator_Generate_Call) RunAndReturn(run func(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time) error) *MockSlotGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
