// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"github.com/google/uuid"
	"github.com/odeyaio/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepository is an autogenerated mock type for the bookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Cancel(ctx context.Context, id uuid.UUID) (model.Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockBookingRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingRepository_Expecter) Cancel(ctx any, id any) *MockBookingRepository_Cancel_Call {
	return &MockBookingRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockBookingRepository_Cancel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Cancel_Call) Return(booking model.Booking, err error) *MockBookingRepository_Cancel_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Booking, error)) *MockBookingRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Create(ctx context.Context, booking *model.Booking) error {
	ret := _mock.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Booking) error); ok {
		r0 = returnFunc(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - booking *model.Booking
func (_e *MockBookingRepository_Expecter) Create(ctx any, booking any) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, booking)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(ctx context.Context, booking *model.Booking)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Booking
		if args[1] != nil {
			arg1 = args[1].(*model.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(err error) *MockBookingRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, booking *model.Booking) error) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) GetByID(ctx context.Context, id uuid.UUID) (model.Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookingRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingRepository_Expecter) GetByID(ctx any, id any) *MockBookingRepository_GetByID_Call {
	return &MockBookingRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_GetByID_Call) Return(booking model.Booking, err error) *MockBookingRepository_GetByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Booking, error)) *MockBookingRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) List(ctx context.Context, limit int, offset int) ([]model.Booking, int, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Booking, int, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []model.Booking); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockBookingRepository_Expecter) List(ctx any, limit any, offset any) *MockBookingRepository_List_Call {
	return &MockBookingRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockBookingRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockBookingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepository_List_Call) Return(bookings []model.Booking, n int, err error) *MockBookingRepository_List_Call {
	_c.Call.Return(bookings, n, err)
	return _c
}

func (_c *MockBookingRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]model.Booking, int, error)) *MockBookingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) ListByUser(ctx context.Context, userID uuid.UUID, from time.Time) ([]model.Booking, error) {
	ret := _mock.Called(ctx, userID, from)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]model.Booking, error)); ok {
		return returnFunc(ctx, userID, from)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []model.Booking); ok {
		r0 = returnFunc(ctx, userID, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, from)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockBookingRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
func (_e *MockBookingRepository_Expecter) ListByUser(ctx any, userID any, from any) *MockBookingRepository_ListByUser_Call {
	return &MockBookingRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, from)}
}

func (_c *MockBookingRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time)) *MockBookingRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepository_ListByUser_Call) Return(bookings []model.Booking, err error) *MockBookingRepository_ListByUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, from time.Time) ([]model.Booking, error)) *MockBookingRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingSlotRepository creates a new instance of MockBookingSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingSlotRepository {
	mock := &MockBookingSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingSlotRepository is an autogenerated mock type for the bookingSlotRepository type
type MockBookingSlotRepository struct {
	mock.Mock
}

type MockBookingSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingSlotRepository) EXPECT() *MockBookingSlotRepository_Expecter {
	return &MockBookingSlotRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockBookingSlotRepository
func (_mock *MockBookingSlotRepository) GetByID(ctx context.Context, id uuid.UUID) (model.Slot, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Slot, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Slot); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Slot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingSlotRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookingSlotRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingSlotRepository_Expecter) GetByID(ctx any, id any) *MockBookingSlotRepository_GetByID_Call {
	return &MockBookingSlotRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingSlotRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingSlotRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingSlotRepository_GetByID_Call) Return(slot model.Slot, err error) *MockBookingSlotRepository_GetByID_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockBookingSlotRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Slot, error)) *MockBookingSlotRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomRepository is an autogenerated mock type for the roomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) Create(ctx context.Context, room *model.Room) error {
	ret := _mock.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Room) error); ok {
		r0 = returnFunc(ctx, room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *model.Room
func (_e *MockRoomRepository_Expecter) Create(ctx any, room any) *MockRoomRepository_Create_Call {
	return &MockRoomRepository_Create_Call{Call: _e.mock.On("Create", ctx, room)}
}

func (_c *MockRoomRepository_Create_Call) Run(run func(ctx context.Context, room *model.Room)) *MockRoomRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Room
		if args[1] != nil {
			arg1 = args[1].(*model.Room)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_Create_Call) Return(err error) *MockRoomRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_Create_Call) RunAndReturn(run func(ctx context.Context, room *model.Room) error) *MockRoomRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) List(ctx context.Context) ([]model.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) List(ctx any) *MockRoomRepository_List_Call {
	return &MockRoomRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomRepository_List_Call) Run(run func(ctx context.Context)) *MockRoomRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_List_Call) Return(rooms []model.Room, err error) *MockRoomRepository_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Room, error)) *MockRoomRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepo creates a new instance of MockScheduleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepo {
	mock := &MockScheduleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleRepo is an autogenerated mock type for the scheduleRepo type
type MockScheduleRepo struct {
	mock.Mock
}

type MockScheduleRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepo) EXPECT() *MockScheduleRepo_Expecter {
	return &MockScheduleRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockScheduleRepo
func (_mock *MockScheduleRepo) Create(ctx context.Context, schedule model.Schedule) error {
	ret := _mock.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Schedule) error); ok {
		r0 = returnFunc(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduleRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScheduleRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule model.Schedule
func (_e *MockScheduleRepo_Expecter) Create(ctx any, schedule any) *MockScheduleRepo_Create_Call {
	return &MockScheduleRepo_Create_Call{Call: _e.mock.On("Create", ctx, schedule)}
}

func (_c *MockScheduleRepo_Create_Call) Run(run func(ctx context.Context, schedule model.Schedule)) *MockScheduleRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Schedule
		if args[1] != nil {
			arg1 = args[1].(model.Schedule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleRepo_Create_Call) Return(err error) *MockScheduleRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduleRepo_Create_Call) RunAndReturn(run func(ctx context.Context, schedule model.Schedule) error) *MockScheduleRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotGenerator creates a new instance of MockSlotGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotGenerator {
	mock := &MockSlotGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotGenerator is an autogenerated mock type for the slotGenerator type
type MockSlotGenerator struct {
	mock.Mock
}

type MockSlotGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotGenerator) EXPECT() *MockSlotGenerator_Expecter {
	return &MockSlotGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockSlotGenerator
func (_mock *MockSlotGenerator) Generate(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time) error {
	ret := _mock.Called(ctx, schedule, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Schedule, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, schedule, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSlotGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockSlotGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule model.Schedule
//   - from time.Time
//   - to time.Time
func (_e *MockSlotGenerator_Expecter) Generate(ctx any, schedule any, from any, to any) *MockSlotGenerator_Generate_Call {
	return &MockSlotGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, schedule, from, to)}
}

func (_c *MockSlotGenerator_Generate_Call) Run(run func(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time)) *MockSlotGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Schedule
		if args[1] != nil {
			arg1 = args[1].(model.Schedule)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotGenerator_Generate_Call) Return(err error) *MockSlotGenerator_Generate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSlotGenerator_Generate_Call) RunAndReturn(run func(ctx context.Context, schedule model.Schedule, from time.Time, to time.Time) error) *MockSlotGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotRepository is an autogenerated mock type for the slotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// ListAvailable provides a mock function for the type MockSlotRepository
func (_mock *MockSlotRepository) ListAvailable(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time) ([]model.Slot, error) {
	ret := _mock.Called(ctx, roomID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]model.Slot, error)); ok {
		return returnFunc(ctx, roomID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []model.Slot); ok {
		r0 = returnFunc(ctx, roomID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotRepository_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type MockSlotRepository_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockSlotRepository_Expecter) ListAvailable(ctx any, roomID any, from any, to any) *MockSlotRepository_ListAvailable_Call {
	return &MockSlotRepository_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, roomID, from, to)}
}

func (_c *MockSlotRepository_ListAvailable_Call) Run(run func(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time)) *MockSlotRepository_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotRepository_ListAvailable_Call) Return(slots []model.Slot, err error) *MockSlotRepository_ListAvailable_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockSlotRepository_ListAvailable_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time) ([]model.Slot, error)) *MockSlotRepository_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRoomRepository creates a new instance of MockSlotRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRoomRepository {
	mock := &MockSlotRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotRoomRepository is an autogenerated mock type for the slotRoomRepository type
type MockSlotRoomRepository struct {
	mock.Mock
}

type MockSlotRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRoomRepository) EXPECT() *MockSlotRoomRepository_Expecter {
	return &MockSlotRoomRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockSlotRoomRepository
func (_mock *MockSlotRoomRepository) GetByID(ctx context.Context, id uuid.UUID) (model.Room, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Room, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Room); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotRoomRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSlotRoomRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSlotRoomRepository_Expecter) GetByID(ctx any, id any) *MockSlotRoomRepository_GetByID_Call {
	return &MockSlotRoomRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSlotRoomRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSlotRoomRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotRoomRepository_GetByID_Call) Return(room model.Room, err error) *MockSlotRoomRepository_GetByID_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockSlotRoomRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Room, error)) *MockSlotRoomRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotCreator creates a new instance of MockSlotCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotCreator {
	mock := &MockSlotCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotCreator is an autogenerated mock type for the slotCreator type
type MockSlotCreator struct {
	mock.Mock
}

type MockSlotCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotCreator) EXPECT() *MockSlotCreator_Expecter {
	return &MockSlotCreator_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type MockSlotCreator
func (_mock *MockSlotCreator) CreateBatch(ctx context.Context, slots []model.Slot) error {
	ret := _mock.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Slot) error); ok {
		r0 = returnFunc(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSlotCreator_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockSlotCreator_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - slots []model.Slot
func (_e *MockSlotCreator_Expecter) CreateBatch(ctx any, slots any) *MockSlotCreator_CreateBatch_Call {
	return &MockSlotCreator_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, slots)}
}

func (_c *MockSlotCreator_CreateBatch_Call) Run(run func(ctx context.Context, slots []model.Slot)) *MockSlotCreator_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Slot
		if args[1] != nil {
			arg1 = args[1].([]model.Slot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotCreator_CreateBatch_Call) Return(err error) *MockSlotCreator_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSlotCreator_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, slots []model.Slot) error) *MockSlotCreator_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}
