// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"github.com/odeyaio/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomRepository is an autogenerated mock type for the roomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) Create(ctx context.Context, room *model.Room) error {
	ret := _mock.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Room) error); ok {
		r0 = returnFunc(ctx, room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *model.Room
func (_e *MockRoomRepository_Expecter) Create(ctx any, room any) *MockRoomRepository_Create_Call {
	return &MockRoomRepository_Create_Call{Call: _e.mock.On("Create", ctx, room)}
}

func (_c *MockRoomRepository_Create_Call) Run(run func(ctx context.Context, room *model.Room)) *MockRoomRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Room
		if args[1] != nil {
			arg1 = args[1].(*model.Room)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_Create_Call) Return(err error) *MockRoomRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_Create_Call) RunAndReturn(run func(ctx context.Context, room *model.Room) error) *MockRoomRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) List(ctx context.Context) ([]model.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) List(ctx any) *MockRoomRepository_List_Call {
	return &MockRoomRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomRepository_List_Call) Run(run func(ctx context.Context)) *MockRoomRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_List_Call) Return(rooms []model.Room, err error) *MockRoomRepository_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Room, error)) *MockRoomRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
