DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS slot;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS booking_status;
DROP TABLE IF EXISTS role;
